"""initial schema

Revision ID: 2cf241c60eb3
Revises: 
Create Date: 2026-07-14 15:31:05.068386
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '2cf241c60eb3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Version-controlled extensions (retired the docker init script).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_repo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('analysis_run',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='run_status', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executive_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_analysis_run_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_run'))
    )
    op.create_index('ix_analysis_run_project_started', 'analysis_run', ['project_id', 'started_at'], unique=False)
    op.create_index('ix_analysis_run_project_status', 'analysis_run', ['project_id', 'status'], unique=False)
    op.create_table('code_unit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('unit_type', sa.String(length=32), nullable=True),
    sa.Column('qualified_name', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('source_code', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('dense_embedding', Vector(1024), nullable=True),
    sa.Column('lexical_index', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_code_unit_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_unit'))
    )
    op.create_index(op.f('ix_code_unit_content_hash'), 'code_unit', ['content_hash'], unique=False)
    op.create_index('ix_code_unit_dense_embedding', 'code_unit', ['dense_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'dense_embedding': 'vector_cosine_ops'})
    op.create_index('ix_code_unit_lexical_index', 'code_unit', ['lexical_index'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_code_unit_project_id'), 'code_unit', ['project_id'], unique=False)
    op.create_table('requirements_doc',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_format', sa.String(length=32), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_requirements_doc_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements_doc'))
    )
    op.create_index(op.f('ix_requirements_doc_project_id'), 'requirements_doc', ['project_id'], unique=False)
    op.create_table('test_unit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('test_name', sa.Text(), nullable=True),
    sa.Column('qualified_name', sa.Text(), nullable=True),
    sa.Column('source_code', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_test_unit_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_unit'))
    )
    op.create_index('ix_test_unit_file_path', 'test_unit', ['file_path'], unique=False)
    op.create_index(op.f('ix_test_unit_project_id'), 'test_unit', ['project_id'], unique=False)
    op.create_table('requirement',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=True),
    sa.Column('external_key', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('req_type', sa.String(length=64), nullable=True),
    sa.Column('is_ambiguous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ambiguity_reason', sa.Text(), nullable=True),
    sa.Column('source_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirement_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['requirements_doc.id'], name=op.f('fk_requirement_doc_id_requirements_doc'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_requirement_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement')),
    sa.UniqueConstraint('project_id', 'external_key', name='external_key')
    )
    op.create_index(op.f('ix_requirement_doc_id'), 'requirement', ['doc_id'], unique=False)
    op.create_index('ix_requirement_project_id', 'requirement', ['project_id'], unique=False)
    op.create_table('trace_link',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('implementation_verdict', sa.Enum('implemented', 'partial', 'missing', 'analysis_error', name='verdict', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('implementation_confidence_band', sa.Enum('high', 'medium', 'low', name='confidence_band', native_enum=False, create_constraint=True, length=10), nullable=True),
    sa.Column('implementation_confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expectation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intelligence_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engineering_risk', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_status', sa.Enum('covered', 'partial', 'uncovered', name='test_status', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('raw_model_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], name=op.f('fk_trace_link_requirement_id_requirement'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_run.id'], name=op.f('fk_trace_link_run_id_analysis_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trace_link')),
    sa.UniqueConstraint('run_id', 'requirement_id', name='run_requirement')
    )
    op.create_index('ix_trace_link_run_id', 'trace_link', ['run_id'], unique=False)
    op.create_table('trace_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_link_id', sa.UUID(), nullable=False),
    sa.Column('code_unit_id', sa.UUID(), nullable=True),
    sa.Column('test_unit_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.Enum('implementation', 'test', name='evidence_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('cited_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.CheckConstraint('(code_unit_id IS NOT NULL) <> (test_unit_id IS NOT NULL)', name=op.f('ck_trace_evidence_exactly_one_unit')),
    sa.ForeignKeyConstraint(['code_unit_id'], ['code_unit.id'], name=op.f('fk_trace_evidence_code_unit_id_code_unit'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_unit_id'], ['test_unit.id'], name=op.f('fk_trace_evidence_test_unit_id_test_unit'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_link_id'], ['trace_link.id'], name=op.f('fk_trace_evidence_trace_link_id_trace_link'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trace_evidence'))
    )
    op.create_index(op.f('ix_trace_evidence_code_unit_id'), 'trace_evidence', ['code_unit_id'], unique=False)
    op.create_index(op.f('ix_trace_evidence_trace_link_id'), 'trace_evidence', ['trace_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_evidence_trace_link_id'), table_name='trace_evidence')
    op.drop_index(op.f('ix_trace_evidence_code_unit_id'), table_name='trace_evidence')
    op.drop_table('trace_evidence')
    op.drop_index('ix_trace_link_run_id', table_name='trace_link')
    op.drop_table('trace_link')
    op.drop_index('ix_requirement_project_id', table_name='requirement')
    op.drop_index(op.f('ix_requirement_doc_id'), table_name='requirement')
    op.drop_table('requirement')
    op.drop_index(op.f('ix_test_unit_project_id'), table_name='test_unit')
    op.drop_index('ix_test_unit_file_path', table_name='test_unit')
    op.drop_table('test_unit')
    op.drop_index(op.f('ix_requirements_doc_project_id'), table_name='requirements_doc')
    op.drop_table('requirements_doc')
    op.drop_index(op.f('ix_code_unit_project_id'), table_name='code_unit')
    op.drop_index('ix_code_unit_lexical_index', table_name='code_unit', postgresql_using='gin')
    op.drop_index('ix_code_unit_dense_embedding', table_name='code_unit', postgresql_using='hnsw', postgresql_ops={'dense_embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_code_unit_content_hash'), table_name='code_unit')
    op.drop_table('code_unit')
    op.drop_index('ix_analysis_run_project_status', table_name='analysis_run')
    op.drop_index('ix_analysis_run_project_started', table_name='analysis_run')
    op.drop_table('analysis_run')
    op.drop_table('project')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS vector")
